---
openapi: 3.1.0
info:
  title: EconomyYakki Server API 문서
  description: EconomyYakki Server API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
security:
  - JWT: []
tags:
  - name: Quiz
    description: 퀴즈 관련 API
  - name: User
    description: 회원가입, 로그인, 로그아웃 API
paths:
  '/api/user/signup':
    post:
      tags:
        - User
      summary: 회원가입 엔드포인트
      description: |
        유저가 회원가입을 합니다.
        - **요청 데이터**: 사용자 이름, 이메일, 비밀번호 포함
        - **응답 데이터**: 회원가입 성공 메시지
      operationId: signUp
      requestBody:
        description: 회원가입 요청 데이터
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/SignUp'
            example:
              email: user@example.com
              username: user or user25
              password: Test1234@
        required: true
      responses:
        '200':
          description: 회원가입 성공
          content:
            '*/*':
              example:
                message: 회원가입이 완료되었습니다.
        '400':
          description: BAD_REQUEST - 비밀번호는 최소 8자 이상, 대•소문자, 숫자, 특수문자를 포함해야 합니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '409':
          description: CONFLICT - 이미 사용 중인 이메일입니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  '/api/user/signin':
    post:
      tags:
        - User
      summary: 로그인 엔드포인트
      description: |
        유저가 로그인을 시도합니다.
        - **요청 데이터**: 이메일, 비밀번호 포함
        - **응답 데이터**: 액세스 토큰 및 리프레시 토큰 반환
      operationId: signIn
      requestBody:
        description: 로그인 요청 데이터
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/SignIn'
            example:
              email: user@example.com
              password: Test1234@
        required: true
      responses:
        '200':
          description: 로그인 성공
          content:
            '*/*':
              example:
                message: 로그인 성공
                accessToken: eyJhbGciOi...
                refreshToken: eyJhbGciOi...
        '400':
          description: BAD_REQUEST - 잘못된 입력값입니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '401':
          description: UNAUTHORIZED - 이메일 또는 비밀번호가 일치하지 않습니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: NOT_FOUND - 사용자를 찾을 수 없습니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  '/api/user/logout':
    post:
      tags:
        - User
      summary: 로그아웃 엔드포인트
      description: |
        유저가 로그아웃을 시도합니다.
        JWT 인증이 돼 있어야 합니다.
        - **헤더 요구사항**: `Authorization: Bearer {access_token}`
        - **응답 데이터**: 로그아웃 성공 메시지
      operationId: logout
      responses:
        '200':
          description: 로그아웃 성공
          content:
            '*/*':
              example:
                message: 로그아웃 완료
        '401':
          description: UNAUTHORIZED - 유효하지 않은 토큰입니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: FORBIDDEN - 접근 권한이 없습니다.
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  '/api/quiz/select-category':
    post:
      tags:
        - Quiz
      summary: 퀴즈 카테고리 선택 엔드포인트
      description: |
        사용자가 원하는 퀴즈 카테고리(사회 및 글로벌 경제, 노동 및 고용 개념, 금융 및 투자 개념, 기본 경제 개념)를 선택합니다.
        이 API는 JWT 인증이 필요하고 선택한 카테고리에 대한 응답을 반환합니다.
      operationId: selectKeyword
      requestBody:
        description: 사용자가 선택한 퀴즈 카테고리 정보
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/QuizCategoryRequestDto'
        required: true
      responses:
        '200':
          description: 퀴즈 카테고리 선택 성공
          content:
            '*/*':
              schema:
                '$ref': '#/components/schemas/QuizCategoryResponseDto'
        '400':
          description: BAD_REQUEST - 유효하지 않은 카테고리 입니다.
          content:
            '*/*':
              schema:
                '$ref': '#/components/schemas/QuizCategoryResponseDto'
        '403':
          description: FORBIDDEN - 접근 권한이 없습니다.
          content:
            '*/*':
              schema:
                '$ref': '#/components/schemas/QuizCategoryResponseDto'
components:
  schemas:
    SignUp:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - email
        - password
        - username
    SignIn:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    QuizCategoryRequestDto:
      type: object
      properties:
        category:
          type: string
    QuizCategoryResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          type: string
  securitySchemes:
    JWT:
      type: http
      name: JWT
      scheme: bearer
      bearerFormat: JWT
